# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  keycloak:
    image: 'entando/entando-keycloak:7.2.0-ENGPM-540-rc1'
    command: [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.profile.feature.scripts=enabled',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/keycloak/data/import',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING', # use 'OVERWRITE_EXISTING' instead if you want to reset your current configuration
        '-Djboss.socket.binding.port-offset=1000',
      ]
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
      - ./keycloak/keycloak-db:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
      - 127.0.0.1:10990:10990
